services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
    ports:
      - 8080:8080
